---
- hosts: all
  vars:
    user_data_file: 'C:/Windows/ansiblevars.yml'
  gather_facts: false



  tasks:
    - name: Load data
      slurp:
        src: "{{ user_data_file | from_yaml }}"
      register: slurped_user_data
    - debug: var=user_data_file

    - name: Decode data and store as fact # You can skip this if you want to use the right hand side directly...
      set_fact:
        user_data: "{{ slurped_user_data | from_yaml }}"




    - name: Make a couple Directories
      win_file:
              path: 'C:\Temp\tcooktess1'
              state: directory
