---
- hosts: all
  vars:
    user_data_file: 'C:\Windows\ansiblevars.json'

  tasks:
    - name: Load data
      slurp:
        src: "{{ user_data_file }}"
      register: slurped_user_data

    - name: Decode data and store as fact # You can skip this if you want to use the right hand side directly...
      set_fact:
        user_data: "{{ slurped_user_data.content|b64decode|from_json }}"
    - debug:
        msg: "{{ slurped_user_data.content | b64decode }}"

    - name: "Re-run setup to use custom facts"
      setup: ~
    
    {% for Directory in user_data %}
    - name: Make a couple Directories
      win_file:
              path: "C:\\Temp\\{{ user_data.Directory }}" 
              state: directory
    {% endfor %} 
