---
- hosts: all
  vars:
    user_data_file: 'C:\Windows\ansiblevars.yml'
  gather_facts: false



  tasks:
    - name: Load data
      slurp:
        src: "{{ user_data_file }}"
      register: slurped_user_data




    - name: Decode data and store as fact # You can skip this if you want to use the right hand side directly...
      set_fact:
        user_data: "{{ slurped_user_data  }}"
    - debug: var=slurped_user_data
    - debug:
        msg: "Public key: {{ slurped_user_data['content'] | to_nice_yaml }}"





    - name: Make a couple Directories
      win_file:
              path: "C:\\Temp\\{{ slurped_user_data }}"
              state: directory
