---
- hosts: all
  vars
    contents: "{{ lookup('file', 'C:\Windows\Temp\ansiblevars') }}"
  gather_facts: false
  tasks:
    - name: Make a couple Directories
      win_file:
              path: "C:\Windows\Temp\script_created\{{Directory1}}"
              state: directory
      win_file:
              path: "C:\Windows\Temp\script_created\{{Directory2}}"
              state: directory
