---
- hosts: all
  vars:
     contents: "{{ lookup('file', 'C:\Windows\Temp\ansiblevars') }}"
  gather_facts: false
  tasks:
    - name: Make a couple Directories
      win_file:
              path: C:\Temp\asdf123
              state: directory
