---
- hosts: all
  vars:
    user_data_file: "C:\Windows\Temp\ansiblevars"
  gather_facts: false
  tasks:
    - name: Make a couple Directories
      win_file:
              path: C:\Temp\jadsf
              state: directory
